id: P000279
initial_creation_type: ocr
created_at: 20/02/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG10287
  title: རྒྱ་གཟའ་བལ་བཟའི་རྣམ་ཐར། ༼དབུ་ཅན་བྲིས་མ།༽
  author: ''
  volumes:
    0665109f9c864a8a8dd9f7b10de41b74:
      image_group_id: I1KG10341
      title: Volume 1 of rgya gza' bal bza'i rnam thar/ (dbu chen bris ma/)
      volume_number: 1
      total_pages: 276
      base_file: v001.txt
